/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:306eb221-26b5-49bd-a9a7-84db78432fe3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_KpoLftRkQ",
    "aws_user_pools_web_client_id": "67jt6eb8o02opvldjkrcpdes0g",
    "oauth": {}
};
export default awsmobile;